PROCESS BEFORE OUTPUT.

 MODULE STATUS_0110.
 MODULE vrm_set_values_0110.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TAB_CONTROL'
  MODULE TAB_CONTROL_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TAB_CONTROL_CHANGE_COL_ATTR.
  LOOP AT   gt_container
       INTO gs_container
       WITH CONTROL TAB_CONTROL
       CURSOR TAB_CONTROL-CURRENT_LINE.
    MODULE TAB_CONTROL_GET_LINES.
*&SPWIZARD:   MODULE TAB_CONTROL_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE screen_status_0110.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TAB_CONTROL'
  LOOP AT gt_container.
    CHAIN.
      FIELD gs_container-MATNR.
      FIELD gs_container-MAKTX.
      FIELD gs_container-QUANT.
      FIELD gs_container-SHIFT.
      FIELD gs_container-DATS.
      FIELD gs_container-USERN.
      FIELD gs_container-DEL.
      MODULE TAB_CONTROL_MODIFY ON CHAIN-REQUEST.
    endchain.
    FIELD gs_container-SEL_LINE MODULE TAB_CONTROL_MARK ON REQUEST.
    FIELD gs_container-matnr MODULE get_maktx ON INPUT.
  ENDLOOP.
  MODULE TAB_CONTROL_USER_COMMAND.
*&SPWIZARD: MODULE TAB_CONTROL_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TAB_CONTROL_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0110.
 MODULE exit_command_0110 AT EXIT-COMMAND.
